Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "docker-course"
  end
  config.vm.provision "shell", inline: <<-SHELL
	apt-get update 
	sudo apt-get install curl -y && curl -fsSL https://get.docker.com/ | bash && docker version  
  SHELL
end
